#pragma once

#define IDI_APP_ICON 101
#define IDR_INTERCEPTION_INSTALLER 201
#define IDR_INTERCEPTION_DLL_X64 202
#define IDR_LAUNCHER_LOGO 203
#define IDR_DEFAULT_BACKGROUND 204
#define IDR_FRONTEND_HTML 301
